repos:
  - repo: local
    hooks:
      - id: test-hook
        name: test-hook
        entry: echo 'test'
        language: system
        stages: [pre-commit]
        pass_filenames: false

      - id: spotless
        name: Spotless Apply & Check
        entry: bash -c "./gradlew spotlessApply && ./gradlew spotlessCheck || exit 1"
        language: system
        stages: [ pre-commit ]
        pass_filenames: false
