repos:
  - repo: local
    hooks:
      - id: spotless-apply
        name: Spotless Apply
        entry: ./gradlew spotlessApply --quiet --no-daemon
        language: system
        stages: [pre-commit]
        pass_filenames: false
        require_serial: true
        always_run: true
