repos:
  - repo: local
    hooks:
      - id: start-hook
        name: start-hook
        entry: echo 'Start pre-commit'
        language: system
        stages: [pre-commit]
        pass_filenames: false
      - id: spotless-apply
        name: Spotless Apply
        entry: ./gradlew spotlessApply
        language: system
        stages: [pre-commit]
        pass_filenames: false
      - id: spotless-check
        name: Spotless Check
        entry: ./gradlew spotlessCheck
        language: system
        stages: [pre-commit]
        pass_filenames: false
